[package]
name = "libzeroengine"
version = "0.1.0"
edition = "2021"

[lib]
name = "libzeroengine"
path = "src/lib.rs"

[[bin]]
name = "dumpucfb"
path = "src/dumpucfb.rs"

[dependencies]
nom = "7.1.3"

[dependencies.lunify]
version = "1.1.0"
features = ["debug"]
